/tmp/slurmd/job51212018/slurm_script: line 0: unalias: pine: not found
/tmp/slurmd/job51212018/slurm_script: line 0: unalias: quota: not found
/tmp/slurmd/job51212018/slurm_script: line 0: unalias: chsh: not found
/tmp/slurmd/job51212018/slurm_script: line 0: unalias: grpe: not found
/tmp/slurmd/job51212018/slurm_script: line 0: unalias: alloc: not found
/tmp/slurmd/job51212018/slurm_script: line 0: unalias: vi: not found
/tmp/slurmd/job51212018/slurm_script: line 0: unalias: chfn: not found
Starting session
2018-10-18 17:31:56.033178: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-10-18 17:31:56.973560: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:08:00.0
totalMemory: 11.17GiB freeMemory: 23.44MiB
2018-10-18 17:31:57.656782: E tensorflow/core/common_runtime/direct_session.cc:158] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 11996954624
/home/casperneo/.conda/envs/clouds/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/casperneo/.conda/envs/clouds/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "experimental/read_to_bin.py", line 48, in <module>
    with tf.Session() as sess:
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1563, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/casperneo/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 633, in __init__
    self._session = tf_session.TF_NewSession(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
